do


local function escape(s)
  return (string.gsub(s, "([^A-Za-z0-9_])", function(c)
    return string.format("%%%02x", string.byte(c))
  end))
end

local function send_title(cb_extra, success, result)
  if success then
    send_msg(cb_extra[1], cb_extra[2], ok_cb, false)
  end
end

local function run(msg, matches)
  local eq = matches[1]
  local url = "http://latex.codecogs.com/gif.latex?\\dpi{150}" .. escape(eq)
  local receiver = get_receiver(msg)
  local title = "LaTeX equation generated by http://www.codecogs.com/latex/eqneditor.php"
  send_photo_from_url(receiver, url, send_title, {receiver, title})
end

return {
  description = "Convert LaTeX equation to image",
  usage = {
    "!tex [equation]: Convert LaTeX equation to image"
  },
  patterns = {
    "!tex (.*)"
  },
  run = run
}

end

